# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab5ce27c5b7cc6c6531681922508f3b3b6e451346adaea14e7048735ba76d4aacfe5970802ac2ad5e79c579c93a634498d74b6f2db1ab0bca6190c1e4d9102c5

test:
  secret_key_base: 4488f330fce6b4ed26d85825bda402a0f1b6248c341e4e369b951ae64f0f14adc8f3717ce15c37e05fd43964dc07772ed47322d290b36ba79cf1d7802bd9ccca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
